@startuml

class Calculadora {
}

class Matriz {
    -matriz[][]
    +Matriz(int[][])
}

class MatrizTraspuesta {
    +trasponer(): void
}

Calculadora ..> Matriz
Matriz <|-- MatrizTraspuesta

@enduml
